export const electricityConsumptionData = {
  "26730028": {
    name: "Moorside",
    maxRating: "50kva",
    totalNumberOfServicedUnits: 20,
    currentUsage: {
      max: {
        Night: 17.5,
        Morning: 18.87,
        Afternoon: 28.51,
        Evening: 31.0,
      },
    },
    projections: [
      {
        timeChunk: "Night",
        currentMaxLoad: 17.5,
        projectedEvLoad: 27.72,
        projectedHeatPumpLoad: 0,
        projectedTotalLoad: 45.22,
        maxRatedLoad: 50,
        "Exceeds?": "No",
      },
      {
        timeChunk: "Morning",
        currentMaxLoad: 18.87,
        projectedEvLoad: 0,
        projectedHeatPumpLoad: 15,
        projectedTotalLoad: 33.87,
        maxRatedLoad: 50,
        "Exceeds?": "No",
      },
      {
        timeChunk: "Afternoon",
        currentMaxLoad: 28.51,
        projectedEvLoad: 0,
        projectedHeatPumpLoad: 15,
        projectedTotalLoad: 43.51,
        maxRatedLoad: 50,
        "Exceeds?": "No",
      },
      {
        timeChunk: "Evening",
        currentMaxLoad: 31,
        projectedEvLoad: 27.72,
        projectedHeatPumpLoad: 0,
        projectedTotalLoad: 58.72,
        maxRatedLoad: 50,
        "Exceeds?": "Yes",
      },
    ],
  },
  "26730050": {
    name: "Ridgemoor",
    maxRating: "25kva",
    totalNumberOfServicedUnits: 15,
    currentUsage: {
      averages: {},
      max: {
        Night: 12.84,
        Morning: 16.71,
        Afternoon: 22.75,
        Evening: 22.52,
      },
    },
    projections: [
      {
        timeChunk: "Night",
        currentMaxLoad: 12.84,
        projectedEvLoad: 27.72,
        projectedHeatPumpLoad: 0,
        projectedTotalLoad: 40.56,
        maxRatedLoad: 25,
        "Exceeds?": "Yes",
      },
      {
        timeChunk: "Morning",
        currentMaxLoad: 16.71,
        projectedEvLoad: 0,
        projectedHeatPumpLoad: 15,
        projectedTotalLoad: 31.71,
        maxRatedLoad: 25,
        "Exceeds?": "Yes",
      },
      {
        timeChunk: "Afternoon",
        currentMaxLoad: 22.75,
        projectedEvLoad: 0,
        projectedHeatPumpLoad: 15,
        projectedTotalLoad: 37.75,
        maxRatedLoad: 25,
        "Exceeds?": "Yes",
      },
      {
        timeChunk: "Evening",
        currentMaxLoad: 22.52,
        projectedEvLoad: 27.72,
        projectedHeatPumpLoad: 0,
        projectedTotalLoad: 50.24,
        maxRatedLoad: 25,
        "Exceeds?": "Yes",
      },
    ],
  },
  "26730039": {
    name: "Braemoor",
    maxRating: "50kva",
    totalNumberOfServicedUnits: 10,
    currentUsage: {
      max: {
        Night: 10.21,
        Morning: 15.22,
        Afternoon: 18.32,
        Evening: 18.18,
      },
    },
    projections: [
      {
        timeChunk: "Night",
        currentMaxLoad: 10.21,
        projectedEvLoad: 27.72,
        projectedHeatPumpLoad: 0,
        projectedTotalLoad: 37.93,
        maxRatedLoad: 50,
        "Exceeds?": "No",
      },
      {
        timeChunk: "Morning",
        currentMaxLoad: 15.22,
        projectedEvLoad: 0,
        projectedHeatPumpLoad: 15,
        projectedTotalLoad: 30.22,
        maxRatedLoad: 50,
        "Exceeds?": "No",
      },
      {
        timeChunk: "Afternoon",
        currentMaxLoad: 18.32,
        projectedEvLoad: 0,
        projectedHeatPumpLoad: 15,
        projectedTotalLoad: 33.32,
        maxRatedLoad: 50,
        "Exceeds?": "No",
      },
      {
        timeChunk: "Evening",
        currentMaxLoad: 18.18,
        projectedEvLoad: 27.72,
        projectedHeatPumpLoad: 0,
        projectedTotalLoad: 45.9,
        maxRatedLoad: 50,
        "Exceeds?": "No",
      },
    ],
  },
};
